spring:
  mail:
    host: smtp.163.com
    username: 13997525738@163.com
    password: HNJRARSIATNPQFAE
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/college
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
